### ISSUE TITLE
bug: argument error after insert

### ISSUE THREAD

**Issue by frankdugan3** [elixir-error-tracker/error-tracker#27]
I'm getting this error:

```elixir
[error] ** (ArgumentError) cannot load `<<152, 139, 52, 172, 79, 76, 17, 239, 181, 22, 11, 103, 23, 163, 197, 255>>` as type :id for field `id` in schema ErrorTracker.Error
    (ecto 3.11.2) lib/ecto/repo/schema.ex:859: Ecto.Repo.Schema.load_each/4
    (ecto 3.11.2) lib/ecto/repo/schema.ex:832: Ecto.Repo.Schema.load_changes/8
    (ecto 3.11.2) lib/ecto/repo/schema.ex:382: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto 3.11.2) lib/ecto/repo/schema.ex:273: Ecto.Repo.Schema.insert!/4
    (hsm 0.9.2) lib/hsm/repo.ex:3: Hsm.Repo.insert!/2
    (error_tracker 0.1.0) lib/error_tracker.ex:122: ErrorTracker.report/3
    (error_tracker 0.1.0) lib/error_tracker/integrations/plug.ex:102: ErrorTracker.Integrations.Plug.report_error/3
    (hsm 0.9.2) lib/hsm_web/endpoint.ex:1: HsmWeb.Endpoint.call/2
    (phoenix 1.7.14) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.5.5) lib/bandit/pipeline.ex:124: Bandit.Pipeline.call_plug!/2
    (bandit 1.5.5) lib/bandit/pipeline.ex:36: Bandit.Pipeline.run/4
    (bandit 1.5.5) lib/bandit/http1/handler.ex:12: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.5.5) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.5.5) /home/frank/git/hsm-rose-fixes/deps/thousand_island/lib/thousand_island/handler.ex:411: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 6.0) gen_server.erl:2163: :gen_server.try_handle_continue/3
    (stdlib 6.0) gen_server.erl:2072: :gen_server.loop/7
    (stdlib 6.0) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

Since it's dealing with the `:id` field, here are my Ecto settings that may be relevant:

```elixir
config :hsm,
  ecto_repos: [Hsm.Repo],
  generators: [binary_id: true]

config :hsm, Hsm.Repo,
  migration_primary_key: [
    name: :id,
    type: :binary_id,
    autogenerate: false,
    read_after_writes: true,
    default: {:fragment, "uuid_generate_v1mc()"}
  ],
  migration_timestamps: [type: :utc_datetime_usec]
```

**Comment by odarriba** [comment]
The fix is available in the v0.1.1 already published.
